<MyButton@Button>:
    color: .8,0,0,1
    size: 100,50
    font_size:32
<Widgets>:

    canvas:
        Rectangle:
            source: "images/precious.jpg"
            size:self.width - self.width * 0.2, self.height - self.height * 0.01
    MyButton:
        text: 'Hello'
        pos:root.x,root.top-self.height
        on_press: root.tell()
    MyButton:
        text: 'World'
        pos: root.right- self.width,root.y



